### ISSUE TITLE
A dev for Psi/Psi+?

### ISSUE THREAD

**Issue by Neustradamus** [gkdr/libomemo#16]
Hello developers of the World,

A lot of users want to have OMEMO in Psi/Psi+, if you can help to do it, it will be perfect!

Thanks in advance.

Tickets:
- https://github.com/psi-im/plugins/issues/10
- https://github.com/psi-im/psi/issues/252
- https://github.com/psi-plus/main/issues/673

Website:
- https://dev.gnupg.org/T3216
- https://www.bountysource.com/issues/40535750-omemo-encryption

**Comment by Neustradamus** [comment]
@stigger

**Comment by tehnick** [comment]
@Neustradamus Please stop spamming.

**Comment by stigger** [comment]
@Neustradamus As I mentioned [here](https://github.com/psi-im/plugins/issues/10#issuecomment-361011306), the OMEMO protocol itself is already implemented, only UI stuff is left, which I'm planning to do soon. libomemo was not used, the implementation uses https://github.com/signalapp/libsignal-protocol-c directly. This issue seems obsolete and probably can be closed.

**Comment by Neustradamus** [comment]
Yes, I have seen your code!
My notification was here for inform you about this ticket and for users/devs that you has worked on OMEMO for Psi/Psi+! :)
It is not spam @tehnick, @Ri0n, @wadealer, @Vitozz.

**Comment by gkdr** [comment]
Closing as suggested by stigger.
