### ISSUE TITLE
Shared library

### ISSUE THREAD

**Issue by tehnick** [gkdr/libomemo#9]
Please add ability to build shared library.

**Comment by gkdr** [comment]
I will once I have some time, I just did not want to make it the standard way because I do not want to expect people to install libs not from they package manager.
How urgent is it?

**Comment by tehnick** [comment]
> I will once I have some time, I just did not want to make it the standard way because I do not want to expect people to install libs not from their package manager.

I failed to parse your sentence. Do you mean that you want to prevent packaging of your library by linux distro maintainers?

> How urgent is it?

It is not urgent. At least for me.

Currently I am only choosing a way how to implement omemo support in our xmpp-client. Maybe we will use your library or another one, maybe we will implement omemo support from scratch...

**Comment by gkdr** [comment]
>I failed to parse your sentence. Do you mean that you want to prevent packaging of your library by linux distro maintainers?

No, not at all. I meant that I do not expect this library to end up packaged. And because people might not want to install libraries from source (so they don't lose track of what is installed, can can cleanly remove everything again), I chose a static lib to be the standard way.

I am planning to also offer a target for a shared lib, but it is currently a low-priority task.

**Comment by mejo-** [comment]
I started looking into packaging lurch for Debian. In order to do so, libomemo would need to be packaged as well. For doing that, a target to build libomemo as a shared library would be very helpful.

**Comment by gkdr** [comment]
this was solved by #30 :slightly_smiling_face:
